PH-1046 make editMandate request delete subdelegated mandates as well
e-gov/PH-sample-provider-python pull request #6
Opened 2024-01-09 09:18 UTC by ArtyomDevNow

[PH-sample-provider-python] Väline päring editMandate peaks tagastama automaatselt lõpetatud volituste nimekirja

2024-01-09 11:18 UTC, aasaru requested changes

2024-01-09 11:18 UTC, aasaru commented on api/app.py
> +        '/v1/representees/<string:representee_identifier>/delegates/<string:delegate_identifier>/mandates/<string:mandate_id>',
representee_id on õige

2024-01-09 12:02 UTC, ArtyomDevNow commented on api/app.py
> +        '/v1/representees/<string:representee_identifier>/delegates/<string:delegate_identifier>/mandates/<string:mandate_id>',
Panin kasutusele person ID-d identifikaatorite asemel.

2024-01-09 12:08 UTC, aasaru requested changes

2024-01-09 12:08 UTC, aasaru commented on api/static/aasaru-x-road-services-consumed-by-paasuke-0.9.3-resolved.json
>        "name": "Licensed under Apache 2.0 license",
remove "aasaru" and version number from the file name.

2024-01-09 12:08 UTC, aasaru commented on README.md
>  ## Configuration
since some of the changes between 0.9.3 and 0.9.9 are unimplemented you should mention that in the readme

2024-01-09 12:08 UTC, aasaru commented on api/services.py
> +def get_deleted_mandates(db, representee_identifier=None, delegate_identifier=None, subdelegated_by_identifier=None):
are you sure this is representee_identifier here and not representee_id?

2024-01-09 12:10 UTC, aasaru requested changes

2024-01-09 12:10 UTC, aasaru commented on tests/pg_data/03d_function_delete_subdelegated_mandates.sql
> +  AND (deleted = FALSE OR deleted IS NULL);
who uses this query?

2024-01-09 12:18 UTC, ArtyomDevNow commented on api/services.py
> +def get_deleted_mandates(db, representee_identifier=None, delegate_identifier=None, subdelegated_by_identifier=None):
Yes, this function uses paasuke_mandates_view and there we have delegate_identifier and representee_identifier columns.

2024-01-09 12:24 UTC, ArtyomDevNow commented on tests/pg_data/03d_function_delete_subdelegated_mandates.sql
> +  AND (deleted = FALSE OR deleted IS NULL);
This query is used in services.py -> delete_subdelegated_mandates_pg function. SELECT query is used to store set of rows related to WHERE clause (deleted subdeleted mandates).

2024-01-11 07:01 UTC, aasaru approved these changes

2024-01-12 04:33 UTC, merged